language: csharp
solution: Sorting.sln

dotnet: 2.0.2
mono: latest

install:
  - nuget restore Sorting.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner


script:
  - dotnet restore
  - dotnet build
  - xbuild /p:Configuration=Release Sorting.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./TestCases/bin/Release/netcoreapp2.0/TestCases.dll
